### ISSUE TITLE
Error when Klippy not connected

### ISSUE THREAD

**Issue by TheLion** [SuperKohl/Moonraker-MQTT-plugin#3]
Hi,

Really like your implementation and configurability of this plugin.

But I do run into 2 issues:

1. I can't get it to startup automatically when the system starts. Not with rc.local and not with `@reboot` in crontab. When run manually, it runs just fine. When starting through rc.local it seems to run one time, only publishing `moonraker/control/run_gcode` to MQTT

2. When Klippy is in a shutdown state, hence, whenever the printer mainboard is shutdown, the script stops, after a while, with an error:

```
[pi@ratos:~]$ python3 /home/pi/Moonraker-MQTT-plugin/scripts/mqtt.py
Traceback (most recent call last):
  File "/home/pi/Moonraker-MQTT-plugin/scripts/mqtt.py", line 43, in <module>
    query_endstops_mqtt = query_endstops.json()
  File "/usr/lib/python3/dist-packages/requests/models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```
Maybe this also happens when auto-starting the scripts, as Klippy is maybe not connected fully when the scripts starts.

**Comment by TheLion** [comment]
> Hey @TheLion,
> 
> first thank you for using my MQTT Moonraker Plugin. I have the same error massage when the printer is not conected. I will fix this bug and publish. Thats for the info
> 
> Malte aka @SuperKohl ✌️

Hi,

Great! Thank you!

Is this, as I suspected, also the reason the automatic startup doesn't work?

**Comment by SuperKohl** [comment]
I compleatly move this into the Moonraker dir. This must fix it (only start when the printer is conected).

**Comment by TheLion** [comment]
I don't understand. Should I move all the files into the Moonraker folder?

**Comment by SuperKohl** [comment]
> I don't understand. Should I move all the files into the Moonraker folder?

No, i make the Script working and work then on a type of plugin marketplace (like octoprin) that make it to install plugin's a lot easyer
